### ISSUE TITLE
Can't mix and match JsonPath and custom function handlers

### ISSUE THREAD

**Issue by tgolden-andplus** [serialized-io/client-js#11]
https://github.com/serialized-io/client-js/blob/master/lib/ProjectionsClient.ts#L86 defines the `handlers` array of a projection request as *either* a `JsonPathHandler[]` or a `CustomPathHandler[]`, which means all handlers must follow the same form. It's my understanding that the underlying projections API does *not* require this and that the types are simply too restrictive. I think it should be something like:

```
type ProjectionHandler = JsonPathHandler | CustomPathHandler;
handlers: ProjectionHandler[]
```

**Comment by mattiasholmqvist** [comment]
Thanks for the comment @tgolden-andplus!

We haven't seen a big need for mixing different handlers within the same projection and actually the underlying API does not support it as of now. The client reflect what is currently supported by the API but we need to make this more clear in the docs to prohibit further confusion. in the future.

It would in theory be possible to support a mixed scenario but we haven't seen this as an important feature. It seems to me it would be hard to maintain and might easily become a bit too complex. I would lean towards going fully custom if JsonPath is. not sufficient.

Do you have an actual scenario at hand where you think that this would be useful for you?

**Comment by tgolden-andplus** [comment]
I'm building a risk-adjusted burnup based on sprint data coming from Jira, so my events reflect the different changes in scope that occur within a version, as well as when a sprint is closed out. So some events are simple to handle with JsonPath, but others require more complex business logic than simple arithmetic can handle, or I need to set fields in the projection whose names are not the same as those in the event...I can certainly make custom endpoints to handle the "simple" events too, but it does surprise me that the API needs them to be all one way or the other.

Specifically, let's say a new project is created in Jira -- that's a simple `merge` for the `ProjectConceived` handler on the projection to set the project ID from the event on the projection. But when a new release is planned, I need to calculate the expected number of sprints from the start and end date that are in my event (this logic is "dumb" for now and will get smarter over time, hence why I don't precalculate it and store that in the event payload) -- that calculation of number of weekdays will live in a custom function endpoint.

**Comment by mattiasholmqvist** [comment]
Thanks for the explanation. I understand your use case I think and we've had similar cases come up in the past. In those cases we decided to do it completely custom since it makes the code a bit more contained. Easier to maintain, test and so on.

However, I think it should not be a big task to support the mixed scenario so let us have a look what the impact will be and we'll get back to you.

**Comment by jeham** [comment]
If the calculation of the expected number of sprints is a core concept in your application, maybe it should be part of the domain logic and included in the events, even if the calculation logic improves over time. That way you can always know what the calculation result was at any given point in time.
Each time the calculation logic is imporoved (or periodically) you could do a re-calculation and emit new events with updated values.

Another design would be to simply create a parallel projection definition for this and load both projections in parallel from the UI.

Yet another one, if the calculation logic changes more often than the actual aggregate, is to simply calculate the value on-the-fly, on query. Of course that's only possible if the calculation is fast enough.
