### ISSUE TITLE
Projections client does not yet support filtering on reference field

### ISSUE THREAD

**Issue by tgolden-andplus** [serialized-io/client-js#7]
See https://docs.serialized.io/api-reference/apis/projections/examples/adding-filter-support-to-projections -- the underlying REST API supports a `reference` query parameter for non-aggregated projections.

However, you can't add this parameter through the Typescript/Javascript client. Callers are required to write their own HTTP request handling code when using projections with reference fields if they want to use those fields as filters.

**Comment by mattiasholmqvist** [comment]
Fixed in version [3.12.3](https://github.com/serialized-io/client-js/releases/tag/v3.12.3).
