### ISSUE TITLE
JsonPathFunction type doesn't include rawData

### ISSUE THREAD

**Issue by tgolden-andplus** [serialized-io/client-js#9]
https://github.com/serialized-io/client-js/blob/master/lib/ProjectionsClient.ts#L63 omits the `rawData` property, which is legal for a subset of JsonPath functions in the docs, such as `set`: https://docs.serialized.io/api-reference/apis/projections/event-handlers#set

(In this particular case, I'd like to preemptively set an empty array that other handlers will append/remove from, so that when my calling code examines the projection before any items are added it can just look at an empty array and not have to handle the unset property.)

**Comment by mattiasholmqvist** [comment]
We'll take a look at this promptly. Thanks for reporting it.

**Comment by mattiasholmqvist** [comment]
Fixed in [3.12.4](https://github.com/serialized-io/client-js/releases/tag/v3.12.4)
